secretGenerator:
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD   # Replace YOUR_PASSWORD with the password you want to use

resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  - mysql-pv-claim.yaml
  - wp-pv-claim.yaml
